[window]
opacity = 0.98
blur = true
decorations= "Full"
decorations_theme_variant = "Dark"

[font]
size = 12
normal.family = "FiraCode Nerd Font"


[terminal]

[terminal.shell]
program = "/usr/local/bin/fish"
