#import = [
#    "~/.config/alacritty/themes/themes/dracula.toml"
#]

[window]
opacity = 0.95

[font]
size = 12.0
normal.family = "CaskaydiaCove NF"
bold.family = "CaskaydiaCove NF"
italic.family = "CaskaydiaCove NF"

[shell]
program = "/usr/bin/fish"
